use dirtybase_contract::db_contract::{
    TableModel,
    types::{ArcUlidField, NumberField, StringField, UlidField},
};
use dirtybase_db::{
    field_values::FieldValue,
    types::{AutoGeneratedIntegerField, CreatedAtField, OptionalInternalIdField},
};
use dirtybase_db_macro::DirtyTable;

#[derive(Debug, Clone, Default, DirtyTable, serde::Serialize)]
#[dirty(no_soft_delete)]
pub(crate) struct Customer {
    pub internal_id: AutoGeneratedIntegerField,
    pub id: UlidField,
    pub name: StringField,
}

#[derive(Debug, Clone, Default, DirtyTable, serde::Serialize)]
pub(crate) struct SalesOrder {
    pub internal_id: AutoGeneratedIntegerField,
    pub id: UlidField,
    pub customer_id: UlidField,
}

#[derive(Debug, Clone, Default, DirtyTable, serde::Serialize)]
pub(crate) struct OrderItem {
    pub internal_id: AutoGeneratedIntegerField,
    pub id: UlidField,
    pub sales_order_id: UlidField,
    pub product_id: UlidField,
    pub name: StringField,
}

#[derive(Debug, Clone, Default, DirtyTable, serde::Serialize)]
pub(crate) struct Invoice {
    pub internal_id: AutoGeneratedIntegerField,
    pub id: UlidField,
    pub sales_order_id: UlidField,
    pub paid: NumberField,
    pub total: NumberField,
}

#[derive(Debug, Clone, Default, DirtyTable, serde::Serialize)]
pub(crate) struct Warehouse {
    pub internal_id: AutoGeneratedIntegerField,
    pub id: UlidField,
    pub name: StringField,
}

#[derive(Debug, Clone, Default, DirtyTable, serde::Serialize)]
pub(crate) struct Product {
    pub internal_id: AutoGeneratedIntegerField,
    pub id: UlidField,
    pub sku: StringField,
}

#[derive(Debug, Clone, Default, DirtyTable, serde::Serialize)]
pub(crate) struct Inventory {
    pub id: OptionalInternalIdField,
    pub warehouse_id: UlidField,
    pub product_id: UlidField,
    pub quantity: NumberField,
}

/*
images
    id - integer
    url - string
    imageable_id - integer
    imageable_type - string
    "xzy", "product"
*/

#[derive(Debug, Clone, Default, DirtyTable, serde::Serialize)]
pub(crate) struct Image {
    pub internal_id: AutoGeneratedIntegerField,
    pub id: ArcUlidField,
    pub url: StringField,
    pub imageable_id: UlidField,
    pub imageable_type: String,
    pub created_at: CreatedAtField,
}

impl Image {
    pub fn make_imageable<T: TableModel>(url: &str, id: &UlidField) -> Self {
        Self {
            internal_id: None,
            id: Default::default(),
            url: url.to_string().into(),
            imageable_id: id.clone(),
            imageable_type: T::table_name().to_string(),
            created_at: Default::default(),
        }
    }
}

#[derive(Debug, Default, Clone, DirtyTable)]
pub struct Address {
    pub id: OptionalInternalIdField,
    pub line_one: String,
    pub line_two: String,
    pub state: String,
}

#[derive(Debug, Default, Clone)]
pub enum CompanyType {
    #[default]
    A,
    B,
    C,
}

impl From<CompanyType> for FieldValue {
    fn from(value: CompanyType) -> Self {
        match value {
            CompanyType::A => "a".into(),
            CompanyType::B => "b".into(),
            CompanyType::C => "c".into(),
        }
    }
}

impl From<FieldValue> for CompanyType {
    fn from(value: FieldValue) -> Self {
        match value {
            FieldValue::String(v) => match v.as_str() {
                "a" => CompanyType::A,
                "b" => CompanyType::B,
                _ => CompanyType::C,
            },
            _ => CompanyType::C,
        }
    }
}

#[derive(Debug, Default, Clone, DirtyTable)]
#[dirty(no_soft_delete)]
pub struct Company {
    pub internal_id: AutoGeneratedIntegerField,
    pub id: UlidField,
    pub name: String,
    #[dirty(flatten)]
    pub address: Address,
    #[dirty(embedded)]
    pub json_address: Address,
    pub company_type: CompanyType,
    pub logo: Vec<u8>,
}

#[derive(Debug, Clone, DirtyTable)]
pub struct Foo {
    pub internal_id: AutoGeneratedIntegerField,
    pub id: UlidField,
    pub data: Vec<u8>,
    pub amount: f64,
    pub count: i64,
}

impl Default for Foo {
    fn default() -> Self {
        Self {
            internal_id: None,
            id: UlidField::default(),
            data: b"This is a test..".to_vec(),
            amount: 100.5_f64,
            count: 1,
        }
    }
}
